branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: flockApp
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
